### ISSUE TITLE
fix bug in extracting pAis from the genome

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/polyA#41]

**Comment by mplass** [comment]
change window to 10 nt instead of 9

A nucleotide is not the first nucleotide in the interval
ex: chr9     16423   16435   .       +

T nucleotide is not the last nucleotide in the interval
ex: chr9    10490   10502   .       -

wrong bed format. Missing score field
ex:  chr9     13973   13983   .       +
should be  chr9     13973   13983   .          .      +

merged polyA file with annotation: wrong bed format. strand should be last field
ex: chr9    152033  152078  ENSG00000172785|CBWD1   -       .

**Comment by nukappa** [comment]
original bug of merging opposite strands pAis fixed [in commited change].
window was already an option in function.
intervals don't need to start or end with A or T, in some cases they can't i.e. CGCC'TTTGTTTTCCCC'
