### ISSUE TITLE
no pAi genes found 

### ISSUE THREAD

**Issue by mschilli87** [rajewsky-lab/polyA#67]
While working on #60, I tried to manually rebuild `test_data/single_utr_no_pAi_genes.txt` (see https://github.com/rajewsky-lab/polyA/pull/64#issuecomment-226407987) using the commands suggest in https://github.com/rajewsky-lab/polyA/pull/64#issuecomment-226303768.

However, starting with a clean repo, running `python3 pipeline.py` generates an _empty_ `test_data/output/pAi_gene.bed` (`test_data/output/pAi.bed` is not empty though).
1. Can you reproduce this?
2. Can you fix this?

**Comment by nukappa** [comment]
yes, i reproduced it. 
please make a small change in your repo and fix it in your next push, it's stemming from the fact that the gtf file names the chromosome as "9" instead of "chr9". [version 83 or full had chr9].

the bug is in function extract_pAi_from_genome, line 199 , change it to
chromosome = str(line.split()[0][1:])
without the 'chr' prefix :)

**Comment by mschilli87** [comment]
Sara & me are in a meeting right now, but I'll add this asap.
